### PR TITLE
Update NPM dependencies to fix depending on vulnerable versions

### PR DESCRIPTION
**Pull request by kkaefer**

### CODE REVIEW

**Comment by mantrajsframework** [comment]
Hi, that changes have not been published via a new version at NPM, right? In 5.0.2, still those messages about vulnerabilities are shown.

**Comment by TyPh00nCdr** [comment]
You don't have to wait for it to get published. You can just depend on the git repository:
* latest `master`: `npm install mapbox/node-sqlite3`
* fix current commit on master: `npm install mapbox/node-sqlite3#918052b`
* this PR: `npm install mapbox/node-sqlite3#update-npm-dependencies`
* fix PR's current commit: `npm install mapbox/node-sqlite3#8fd29bc`

**Comment by daniellockyer** [comment]
This should be coming as part of the upcoming release so I'll close this for now 🙂

**Comment by daniellockyer** [comment]
This should be coming as part of the upcoming release so I'll close this for now 🙂

**Pull request closed without merging**
