### PR TITLE
port to be used on z/OS

### PR DESCRIPTION
**Pull request by jBarz**
Use nan 2.5.0
Use xlc options instead of gcc options.
Avoid use of python tar functionality. Use shell instead.

### CODE REVIEW

**Comment by springmeyer** [comment]
How can this change be tested on travis? Is there a docker image available for z/OS?

**Comment by jBarz** [comment]
Unfortunately, we don't have community zos systems at the moment but we are working on making some available in the near future

**Comment by springmeyer** [comment]
> Unfortunately, we don't have community zos systems at the moment but we are working on making some available in the near future

Okay, I'm hesitant to accept a PR that I can't confirm works. Is there a way for me to be able to test?

**Comment by daniellockyer** [comment]
This PR is out-of-date with how `node-sqlite3` currently works and builds. If it's still an issue, feel free to open a new PR with the updated method 🙂

**Pull request closed without merging**
