### PR TITLE
Add TRY_CATCH_CALL function check and remove Nan::MakeCallback

### PR DESCRIPTION
**Pull request by xbolshe**
Signed-off-by: Eugene Bolshakov pub@relvarsoft.com

This patch fixes 2 issues:
1. There is no check for a callback function presence in TRY_CATCH_CALL
2. Remove Nan::MakeCallback due to https://github.com/nodejs/nan/issues/284 and use Nan::Call

### CODE REVIEW

**Comment by xbolshe** [comment]
It is better to use Nan::Call due to v8 differences.

**Comment by springmeyer** [comment]
@xbolshe - thank you for this fix. It looks like in #665 you also have a testcase that failed before this PR. Can you add that as well?

**Comment by xbolshe** [comment]
If you mean this post https://github.com/mapbox/node-sqlite3/issues/665#issuecomment-228177620, it does not related with node-sqlite3. The issue was related with a MMX support on the target CPU (it does not support MMX). The issue was fixed after a compilation with disabling MMX.

**Comment by daniellockyer** [comment]
This library has since switched away from NAN so this should no longer be relevant - closing for now 🙂

**Pull request closed without merging**
