### PR TITLE
Fix addListener('insert/update/delete') events

### PR DESCRIPTION
**Pull request by 131**
The `addListener('insert /update/delete') API throw 
```
Error: update is not a valid configuration option
    at Database.addListener.Database.on (D:\dvp\study_stack\cloudfs\node_modules\sqlite3\lib\sqlite3.js:154:14)
    at SQLITE.on (D:\dvp\study_stack\cloudfs\libs\sql.js:74:15)
    at test.run (D:\dvp\study_stack\cloudfs\test.js:12:14)
    at <anonymous> Error: update is not a valid configuration option
    at Database.addListener.Database.on (D:\dvp\study_stack\cloudfs\node_modules\sqlite3\lib\sqlite3.js:154:14)
    at SQLITE.on (D:\dvp\study_stack\cloudfs\libs\sql.js:74:15)
    at test.run (D:\dvp\study_stack\cloudfs\test.js:12:14)
    at <anonymous>
```

The following adjustement in Database::Configure make it work !

### CODE REVIEW

**Comment by 131** [comment]
I can add tests & documentation if requested

**Comment by kewde** [comment]
Thank you for your pull request.
Additional tests and documentation are required for small changes to make sure that it works as intended.

**Comment by little-brother** [comment]
Any updates?

**Comment by daniellockyer** [comment]
Hey @131, this uses NAN but we've since switched to N-API. Would you be able to rework your PR? 🙂

**Pull request closed without merging**
