### PR TITLE
Added support for setting SQLite limits

### PR DESCRIPTION
**Pull request by paulfitz**
This extends `db.configure` to support the [`sqlite3_limit`](https://www.sqlite.org/c3ref/limit.html) method.

Calling `db.configure('limit', sqlite3.LIMIT_XXX, value)` is now equivalent to calling `sqlite3_limit(db, SQLITE_LIMIT_XXX, value)`. For example, to prohibit attaching extra databases on a given database connection, you'd call `db.configure('limit', sqlite3.LIMIT_ATTACHED, 0)`. The list of possible limits is taken from https://www.sqlite.org/c3ref/c_limit_attached.html

This is useful for selectively reducing limits. It cannot increase limits set at compile-time.

### CODE REVIEW

**Comment by paulfitz** [comment]
The single test failure looks unrelated:
Screenshot from 2022-03-03 10-15-19
Other runs look happier:
Screenshot from 2022-03-03 10-17-38

**Comment by daniellockyer** [comment]
@paulfitz Would you be able to rebase the PR? 🙂

**Comment by paulfitz** [comment]
@daniellockyer I've rebased the PR.

**Comment by joebnb** [comment]
waiting for this feature come

**Pull request merged**
