### PR TITLE
Adding promise support

### PR DESCRIPTION
**Pull request by Aminadav**
See this code for example:
```
init() 

async function init(){
	var db=new sqlite3.Database('candelete.db')
	await db.runAsync('create table abc (c tinyint)')
	await db.runAsync('insert into abc values (3)')
	var result = await db.allAsync('select * from abc')
	console.log(result)  // {[a:3]}
}
```

### CODE REVIEW

**Comment by tmcw** [comment]
I think we should [drop node 0.10](https://github.com/mapbox/node-sqlite3/issues/719) and use native promises rather than Bluebird.

**Comment by Aminadav** [comment]
Native promise do not have `Promisfiy` function.
Until you drop support, you can give the users Promises out of the box






[image: photo]
*Aminadav Glickshtein*
<https://mailtrack.io/trace/link/d5918bcde395a876ed0240c4f6cf59c7d7dadc81?url=http%3A%2F%2Fwww.facebook.com%2Faminadav.g%2F&signature=1e34ac54bba18787>

<https://mailtrack.io/trace/link/8b446897cad94097c70cbfeaebf91e9dc5279b32?url=http%3A%2F%2Flinkedin.com%2Fin%2Faminadavg&signature=75a5fe7cbd7c7035>

<https://mailtrack.io/trace/link/d7c007409ca1ab485649ad1230a139ed63c03852?url=http%3A%2F%2Ftwitter.com%2FAminadavG&signature=9a62c21f3a8ef003>

<https://mailtrack.io/trace/link/16c11a8e1f3434a8c6eb85d962217653f5ee1f39?url=http%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCCQxUMzjB3m9jA3uObx3vLg&signature=08cc671864b5c91a>

<https://mailtrack.io/trace/link/6fcbf7d5dfd68b104e0e6a2e786a5852e1c4bf21?url=http%3A%2F%2Fangel.co%2Faminadav-glickshtein&signature=6d58f2eb895a96aa>

<https://mailtrack.io/trace/link/17aab80ff4b54d3c3b48987ae5557fdc6f7bc943?url=http%3A%2F%2Fstackoverflow.com%2Fusers%2F1229624%2Faminadav&signature=794eabbd110b5cd6>

<https://mailtrack.io/trace/link/df81350c0df4b71721291e21c96d3311200c72a6?url=http%3A%2F%2Fgithub.com%2Faminadav&signature=dd9b9f52818d2e05>

**Comment by mceachen** [comment]
@Aminadav [pify](https://github.com/sindresorhus/pify) has no deps and gives you promisify.

**Comment by daniellockyer** [comment]
Closing as the PR is stale and I'd prefer not to add Bluebird. I'll see what the best native way is now 🙂

**Pull request closed without merging**
