### PR TITLE
Added library types file

### PR DESCRIPTION
**Pull request by bpasero**

### CODE REVIEW

**Comment by mojoaxel** [comment]
@bpasero Thanks! I hope this will get merged!
Also we should update this to the current version. Need help?

**Comment by daniellockyer** [comment]
Hey @bpasero! 👋🏻 Happy to get this merged 🙂

Would you be able to rebase the PR?

**Comment by bpasero** [comment]
@mojoaxel this is pretty much a snapshot of the version at https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/sqlite3/index.d.ts, I am unfortunately not having the energy right now to make the changes for API additions if there are any.

@daniellockyer rebased!

**Comment by daniellockyer** [comment]
Thanks @bpasero! I'll look at updating the file before the next release 🙂

**Pull request merged**
